---
title: Mathias Menzl
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mathias.menzl@gmail.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ''
url: http://www.mathiasmenzl.com
twitter_username: mathiasmenzl
github_username: matmenzl
linkedin_username: mathiasmenzl
facebook_username: mathias.menzl
markdown: kramdown
contentful:
  spaces:
  - example:
      space: c6w6ow3yerko
      access_token: b1aa54d8e1e58a72193b88f01d652ce8f8588331ed763aa8deb1ea36a65acacd
      cda_query:
        include: 2
        limit: 100
      content_types:
        cat: MyCoolMapper
      client_options:
        api_url: preview.contentful.com
      base_path: app_path
